name: JFrog Conan CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simple-cpp-conan-app

    steps:
      - uses: actions/checkout@v4

      # Install Conan (pinned version for stability)
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==2.26.0

      - name: Check Conan version
        run: conan --version

      # Detect default profile
      - name: Configure Conan profile
        run: conan profile detect --force

      # Add and authenticate JFrog remote
      - name: Add JFrog remote
        run: |
          conan remote add jfrog https://trialzi92ft.jfrog.io/artifactory/api/conan/conan-virtual --force
          conan remote login jfrog ${{ secrets.JF_USERNAME }} -p ${{ secrets.JF_ACCESS_TOKEN }}

      # Create and build the package (this also installs dependencies automatically)
      - name: Create Conan Package
        run: |
          conan create . --build=missing -s build_type=Release

      # Upload only your package (not everything)
      - name: Upload Package to JFrog
        run: |
          conan upload myapp/0.1.0 --remote=jfrog --confirm