name: JFrog Conan CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simple-cpp-conan-app

    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Check Conan version
        run: conan --version

      - name: Add JFrog remote
        run: |
          conan remote add jfrog https://trialzi92ft.jfrog.io/artifactory/api/conan/conan-virtual --force
          conan login -r jfrog -u ${{ secrets.JF_USERNAME }} -p ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Install Dependencies
        run: |
          conan install . --output-folder=build --build=missing

      - name: Configure CMake
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build

      - name: Create Conan Package
        run: |
          conan create . --build=missing

      - name: Upload Package to JFrog
        run: |
          conan upload "*" --remote=jfrog --confirm