name: JFrog NPM CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simple-node-js-react-npm-app-master

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: simple-node-js-react-npm-app-master/package-lock.json


      - name: Configure npm for JFrog
        run: |
          echo "registry=https://trialzi92ft.jfrog.io/artifactory/api/npm/npm-virtual/" > .npmrc
          echo "always-auth=true" >> .npmrc
          echo "//trialzi92ft.jfrog.io/artifactory/api/npm/npm-virtual/:_authToken=${JF_ACCESS_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Verify registry
        run: npm config get registry

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build


      - name: Publish Package
        run: npm publish --registry=https://trialzi92ft.jfrog.io/artifactory/api/npm/npm-local/